spring.application.name=Eureka
# Server Port (8761 is the standard default for Eureka)
server.port=8761

# Application Name


# Disable self-registration (Prevents the server from acting as its own client)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Dashboard & Service URL Configuration
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
