spring.application.name=Api-gateway
server.port=8000
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=false

# Define static routes for Product Service
spring.cloud.gateway.routes[0].id=Product
spring.cloud.gateway.routes[0].uri=lb://PRODUCT
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**

# Define static routes for Order Service
spring.cloud.gateway.routes[1].id=Orders
spring.cloud.gateway.routes[1].uri=lb://ORDERS
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
