spring.application.name=Eureka
# Eureka Server Port
server.port=8761

# Prevent the Eureka Server from registering itself as a client
eureka.client.register-with-eureka=false

# Prevent the Eureka Server from fetching the registry (since it hosts it)
eureka.client.fetch-registry=false

# Point to its own default zone for service URLs
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


